In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
iris = sns.load_dataset('iris')

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
titanic = sns.load_dataset('titanic')

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [5]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [7]:
penguins = sns.load_dataset('penguins')
penguins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

- Encoding

In [9]:
# label encoding
# column that you can encode

penguins['species'].unique()

# {  }

species_codes = {
    'Adelie': 0,
    'Chinstrap': 1,
    'Gentoo': 2
}

penguins['species_encoded'] = penguins['species'].map(species_codes)

penguins.sample(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male,0
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,Male,0
189,Chinstrap,Dream,52.0,20.7,210.0,4800.0,Male,1
312,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,Female,2
277,Gentoo,Biscoe,45.5,15.0,220.0,5000.0,Male,2
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male,0
304,Gentoo,Biscoe,44.9,13.8,212.0,4750.0,Female,2
252,Gentoo,Biscoe,45.1,14.5,207.0,5050.0,Female,2
175,Chinstrap,Dream,50.6,19.4,193.0,3800.0,Male,1
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male,2

In [ ]:
# pandas map

In [13]:
penguins['island'].unique()

# {  }

island_codes = {
    'Torgersen': 0,
    'Dream': 1,
    'Biscoe': 2
}

penguins['island_encoded'] = penguins['island'].map(island_codes)

penguins.sample(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_encoded,island_encoded
88,Adelie,Dream,38.3,19.2,189.0,3950.0,Male,0,1
144,Adelie,Dream,37.3,16.8,192.0,3000.0,Female,0,1
231,Gentoo,Biscoe,49.0,16.1,216.0,5550.0,Male,2,2
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,Female,0,2
315,Gentoo,Biscoe,50.8,15.7,226.0,5200.0,Male,2,2
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,Female,2,2
154,Chinstrap,Dream,51.3,19.2,193.0,3650.0,Male,1,1
192,Chinstrap,Dream,49.0,19.5,210.0,3950.0,Male,1,1
163,Chinstrap,Dream,51.7,20.3,194.0,3775.0,Male,1,1
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,Female,0,2

In [ ]:
# factorize
# species still contains the species names

# factorize will take the column and assigns to the new groups
pd.factorize(penguins['species'])

penguins('species_factorize') = 
# penguins['species_factorize'],unique_penguins = pd.factorize(penguins['species'])
penguins

SyntaxError: cannot assign to function call (2816900969.py, line 7)

- apply the three methods to island column
- manually applying label codes
- using the factorize method
- using the category