### scaling

In [7]:
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler

In [8]:
data = pd.DataFrame({
    'age': [20, 50, 100],
    'income': [20000, 50000, 100000]
})
# upscale/downscale
scaler = MinMaxScaler()
# Normalization 
# you want to check what the data will look like in a scale of 0 to 1.
normalize_data = scaler.fit_transform(data)

df_normalized = pd.DataFrame(normalize_data, columns= ['age', 'income'])
df_normalized

     age  income
0  0.000   0.000
1  0.375   0.375
2  1.000   1.000

- Why do we normalize data?

    - easier to calculate
- a lot prefernce to salary over age in the given example

- our models only use numbers

In [9]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [10]:
std_scaler = StandardScaler()

std_data = std_scaler.fit_transform(data)
# you got the z-score transformations for each data point

In [11]:
data

   age  income
0   20   20000
1   50   50000
2  100  100000

In [12]:
df_std_data = pd.DataFrame(std_data, columns= ['age', 'income'])
df_std_data

        age    income
0 -1.111168 -1.111168
1 -0.202031 -0.202031
2  1.313198  1.313198

Feature Encoding

    - ML models need numbers
- label encoding
- one hot encoding

Feature Scaling

- To avoid bias due to large ranges of some features

    - Normalization
    - Standardization

Titanic???