## One hot encoding

In [11]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
iris = sns.load_dataset('iris')

iris.sample()

    sepal_length  sepal_width  petal_length  petal_width species
22           4.6          3.6           1.0          0.2  setosa

In [4]:
# get dummies method - categories --> Columns
# automatically detects the catagorical columns as well 
df_onehot = pd.get_dummies(iris, columns=['species'])

df_onehot['species_setosa'].dtype

df_onehot.sample(10)

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
84,5.4,3.0,4.5,1.5,False,True,False
53,5.5,2.3,4.0,1.3,False,True,False
52,6.9,3.1,4.9,1.5,False,True,False
55,5.7,2.8,4.5,1.3,False,True,False
122,7.7,2.8,6.7,2.0,False,False,True
143,6.8,3.2,5.9,2.3,False,False,True
66,5.6,3.0,4.5,1.5,False,True,False
82,5.8,2.7,3.9,1.2,False,True,False
56,6.3,3.3,4.7,1.6,False,True,False
126,6.2,2.8,4.8,1.8,False,False,True

Get Dummies, it automatically ignores any missing values

df

In [5]:
df = pd.DataFrame([ 1,2,np.nan,1,1,1,3,3,3,2,2,2,3,3,3,1,1,1,1], columns= ["first"])
df.head()

df['first'].dtype

df['first'] = df['first'].astype('category')
df['first'].dtype

df_encoded = pd.get_dummies(df, columns=['first'], dummy_na=False)
df_encoded.head()
# df_encoded.info()

   first_1.0  first_2.0  first_3.0
0       True      False      False
1      False       True      False
2      False      False      False
3       True      False      False
4       True      False      False

**can also use sklearn.preprocessing method**
- OneHotEncoder
- the other method to to label encoding?????? --> LabelEncoder

In [6]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Creating the encoder
encoder = OneHotEncoder( sparse_output=False, handle_unknown='ignore')

# Ignore the missing values if handle_unknown = 'ignore'"in class label encoding .ipynb"

In [8]:
encoder.fit_transform(iris)

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(150, 126))

In [9]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Creating the encoder
encoder = OneHotEncoder( sparse_output=False, handle_unknown='ignore')

In [10]:
iris_onehot = iris.copy()

encoder = OneHotEncoder( sparse_output = False, handle_unknown='ignore')

catagorical_cols = ['species']

ecoded_values = encoder.fit_transform(iris_onehot[catagorical_cols]) # species

# names of new columns, that don't exist yet
new_columns = encoder.get_feature_names_out(catagorical_cols)
new_columns
# ['species_setosa', 'species_versicolor', 'species_virginica']

# iris_onehot

# adding the columns to the dataframe

iris_onehot[new_columns] = ecoded_values

iris_onehot.drop(columns=['species'], inplace = True)
iris_onehot

,sepal_length,sepal_width,petal_length,petal_width,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,1.0,0.0,0.0
1,4.9,3.0,1.4,0.2,1.0,0.0,0.0
2,4.7,3.2,1.3,0.2,1.0,0.0,0.0
3,4.6,3.1,1.5,0.2,1.0,0.0,0.0
4,5.0,3.6,1.4,0.2,1.0,0.0,0.0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.0,0.0,1.0
146,6.3,2.5,5.0,1.9,0.0,0.0,1.0
147,6.5,3.0,5.2,2.0,0.0,0.0,1.0
148,6.2,3.4,5.4,2.3,0.0,0.0,1.0
149,5.9,3.0,5.1,1.8,0.0,0.0,1.0

pl , pw, sl, sw, species, setosa, virginica, versicolor

Species --> object

drop this column, before fitting into the model

Try to do both.
Label encoding, and one hot encoding on
 
**titanic dataset**

In [ ]:
titanic = sns.load_dataset('titanic')

titanic.sample()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [14]:
dft_onehot = pd.get_dummies(titanic, columns=['sex'])

dft_onehot['sex_male'].dtype

dft_onehot.sample(10)

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
224,1,1,38.0,1,0,90.0000,S,First,man,True,C,Southampton,yes,False,False,True
765,1,1,51.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False,True,False
142,1,3,24.0,1,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False,True,False
220,1,3,16.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,yes,True,False,True
380,1,1,42.0,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True,True,False
48,0,3,NaN,2,0,21.6792,C,Third,man,True,NaN,Cherbourg,no,False,False,True
279,1,3,35.0,1,1,20.2500,S,Third,woman,False,NaN,Southampton,yes,False,True,False
126,0,3,NaN,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,False,True
853,1,1,16.0,0,1,39.4000,S,First,woman,False,D,Southampton,yes,False,True,False
647,1,1,56.0,0,0,35.5000,C,First,man,True,A,Cherbourg,yes,True,False,True

In [15]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [17]:
titanic_onehot = titanic.copy()

encoder = OneHotEncoder( sparse_output = False, handle_unknown='ignore')

catagorical_cols = ['sex']

ecoded_values = encoder.fit_transform(titanic_onehot[catagorical_cols])

new_col_titanic = encoder.get_feature_names_out(catagorical_cols)
new_col_titanic

titanic_onehot[new_col_titanic] = ecoded_values

titanic_onehot.drop(columns=['sex'], inplace = True)
titanic_onehot

,survived,pclass,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_female,sex_male
0,0,3,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,0.0,1.0
1,1,1,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1.0,0.0
2,1,3,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,1.0,0.0
3,1,1,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1.0,0.0
4,0,3,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0.0,1.0
887,1,1,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,1.0,0.0
888,0,3,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,1.0,0.0
889,1,1,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0.0,1.0
890,0,3,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0.0,1.0